'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {wikiData} from '@/lib/wiki';
const names:Record<string,string>={'fe.typescript':'TypeScript','fe.browser':'Browser internals','fe.react':'React','fe.nextjs':'Next.js','fe.http-cache':'HTTP & caching','fe.performance':'Performance','fe.testing':'Frontend testing','fe.accessibility':'Accessibility','fe.architecture':'Frontend architecture','be.java':'Java','be.spring':'Spring Boot','be.rest':'REST API design','be.sql':'SQL','be.transactions':'Transactions','be.auth':'Authentication','be.concurrency':'Concurrency','be.redis':'Redis','be.integration':'Integration testing','ops.linux':'Linux','ops.networking':'Networking','ops.http':'HTTP','ops.nginx':'Nginx','ops.docker':'Docker','ops.kubernetes':'Kubernetes','ops.cicd':'CI/CD','ops.aws':'AWS','ops.observability':'Observability','ops.debugging':'Production debugging'};
const menus=['Overview','Learning tracks','Review queue','Knowledge library','Assessments','Learning journal','Misconceptions','Sources','Exercises'];
const dims=['Understanding','Implementation','Edge cases','Testing','Trade-offs'];
const url=(p:string)=>'/notes/'+p;
export default function Dashboard({data}:{data:ReturnType<typeof wikiData>}) {
 const [page,setPage]=useState('Overview'); const [track,setTrack]=useState('all'); const [query,setQuery]=useState('');
 const skills=Object.entries(data.mastery.skills); const assessed=skills.filter(([,s])=>s.last_assessed_on!==null); const pending=data.queue.items.filter(r=>r.status==='pending'); const due=pending.filter(r=>r.due_on<=data.today);
 const sections:Record<string,string>={'Knowledge library':'concepts','Assessments':'assessments','Learning journal':'daily','Misconceptions':'mistakes','Sources':'sources','Exercises':'exercises'};
 const filtered=data.docs.filter(d=>(query ? true:d.section===sections[page])&&(d.title+' '+d.body).toLowerCase().includes(query.toLowerCase()));
 function navigate(p:string){setPage(p);setQuery('');}
 const reviewList=<div className="review-list">{pending.length===0?<p>No pending reviews.</p>:pending.map(r=><div className="review" key={r.id}><div className="date-box"><strong>{r.due_on.slice(8)}</strong><span>{new Date(r.due_on+'T12:00:00Z').toLocaleDateString('en',{month:'short',timeZone:'UTC'})}</span></div><div><Link href={url(r.concept_ref??r.assessment_refs[0])}>{names[r.skill_id]??r.skill_id}</Link><p>{r.scheduling_reason}</p></div><span className="tag">{r.due_on<data.today?'Overdue':r.due_on===data.today?'Due today':'Upcoming'}</span></div>)}</div>;
 return <div className="shell"><aside><Link className="brand" href="/">✳ <span>fieldnotes<small>ENGINEERING WORKSPACE</small></span></Link><div className="eyebrow nav-label">YOUR LEARNING SYSTEM</div><nav aria-label="Main navigation">{menus.map((m,i)=><button key={m} className={page===m?'active':''} onClick={()=>navigate(m)} aria-current={page===m?'page':undefined}><span className="nav-icon">{['◫','▤','◷','◇','✓','▧','↺','↗','⌘'][i]}</span>{m}{m==='Review queue'&&<b>{pending.length}</b>}</button>)}</nav><div className="sidebar-foot"><span className="dot"/> Evidence over assumptions<p>Small steps. Durable understanding.</p><Link href={url('README.md')}>How this workspace works ↗</Link></div></aside><main className="workspace"><header><div className="breadcrumb">Workspace <span>/</span> {page}</div><label className="search"><span>⌕</span><input aria-label="Search all wiki notes" placeholder="Search your wiki…" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="avatar">J</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">PERSONAL ENGINEERING WIKI</div><h1>{query?'Search your knowledge':page==='Overview'?'A little better, every day.':page}</h1><p>{query?`Results for “${query}”`:page==='Overview'?'Build practical skills. Revisit what matters. Make it stick.':'Your learning history, grounded in actual evidence.'}</p></div><span className="today">{data.today}<small>Asia / Taipei</small></span></div>
 {!query&&page==='Overview'&&<><section className="hero"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>Find your starting point.</h2><p>Your frontend reasoning baseline is recorded. Next, explore backend and DevOps through practical assessments before choosing new lessons.</p><Link className="primary" href={url('assessments/baseline-plan.md')}>View baseline plan <span>↗</span></Link></div><div className="journey"><div className="step done"><span>✓</span><div>Frontend baseline<small>Initial reasoning evidence recorded</small></div></div><div className="step"><span>02</span><div>Backend baseline<small>Next up · not assessed</small></div></div><div className="step"><span>03</span><div>DevOps baseline<small>Then daily practice & reviews</small></div></div></div></section><div className="stats"><div><span>Skills with assessment evidence</span><strong>{assessed.length}<small> / {skills.length}</small></strong><p>Coverage, not a mastery score</p></div><div><span>Reviews due now</span><strong>{due.length}<small> / {pending.length} pending</small></strong><p>Missed days never count as failure</p></div><div><span>Concept notes</span><strong>{data.docs.filter(d=>d.section==='concepts').length}</strong><p>A growing, connected reference</p></div></div><div className="section-title"><h2>Your learning tracks</h2><button className="text-button" onClick={()=>navigate('Learning tracks')}>Explore all skills →</button></div><div className="tracks">{['frontend','backend','devops'].map((t,i)=>{const total=skills.filter(([,s])=>s.track===t).length;const count=assessed.filter(([,s])=>s.track===t).length;return <button className="track-card" key={t} onClick={()=>{navigate('Learning tracks');setTrack(t);}}><div className={'track-symbol t'+i}>{['⌘','{ }','↗'][i]}</div><span className="track-allocation">{[30,35,35][i]}% target allocation</span><h3>{['Frontend engineering','Backend engineering','DevOps & systems'][i]}</h3><p>{['Interfaces, browsers & user experience','APIs, data & application behavior','Infrastructure, delivery & reliability'][i]}</p><div className="progress"><i style={{width:`${count/total*100}%`}}/></div><footer>{count} of {total} skills assessed <span>→</span></footer></button>})}</div><div className="section-title"><h2>Coming back to it</h2><button className="text-button" onClick={()=>navigate('Review queue')}>Review queue →</button></div>{reviewList}</>}
 {!query&&page==='Learning tracks'&&<><div className="filters">{['all','frontend','backend','devops'].map(t=><button aria-pressed={track===t} className={track===t?'selected':''} key={t} onClick={()=>setTrack(t)}>{t==='all'?'All tracks':t}</button>)}</div><p className="notice">Scores are 0–4 per dimension. A dash means not assessed. Reasoning and test design evidence do not establish working implementation.</p><div className="matrix-wrap"><table className="matrix"><thead><tr><th>Skill</th>{dims.map(d=><th key={d}>{d}</th>)}<th>Evidence</th></tr></thead><tbody>{skills.filter(([,s])=>track==='all'||s.track===track).map(([id,s])=><tr key={id}><th>{names[id]??id}<small>{s.track} · {s.status}</small></th>{Object.values(s.latest_scores).map((v,i)=><td key={i}>{v?<Link className={'score score'+v.score} title={`${dims[i]}: ${v.score} / 4 — open assessment evidence`} href={url(v.evidence_ref)}>{v.score}</Link>:<span className="unknown" aria-label="Not assessed">—</span>}</td>)}<td>{s.last_assessed_on??'Not assessed'}</td></tr>)}</tbody></table></div><div className="doc-grid">{data.docs.filter(d=>d.section==='curriculum').map(d=><Link className="doc-card" href={url(d.path)} key={d.path}><span className="eyebrow">CURRICULUM</span><h3>{d.title}</h3><span>Open skill map →</span></Link>)}</div></>}
 {!query&&page==='Review queue'&&<><div className="notice">Successful independent reviews: 1 → 3 → 7 → 14 → 30 days after the preceding success. Gaps get a fresh probe in 1–3 days. Pending stays pending.</div>{reviewList}</>}
 {(query||sections[page])&&<><p className="result-count">{filtered.length} {filtered.length===1?'document':'documents'} · Markdown is the source of truth</p><div className="doc-grid">{filtered.map(d=><Link className="doc-card" href={url(d.path)} key={d.path}><span className="eyebrow">{d.section}</span><h3>{d.title}</h3><p>{d.body.replace(/^#+ .+$/gm,'').replace(/[*`|>]/g,'').trim().slice(0,150)}…</p><span>Read note ↗</span></Link>)}</div>{filtered.length===0&&<p>No notes match this search.</p>}</>}
 <footer className="page-footer">Built for understanding, not streaks.<Link href={url('AGENTS.md')}>Tutor principles ↗</Link></footer></div></main></div>;
}
